spring:
  application:
    name: DirectNexus
  datasource:
    url: jdbc:postgresql://postgres:5432/direct_db
    username: keycloak
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://direct.boostergin.com:9082/realms/DirectNexus
          jwk-set-uri: https://direct.boostergin.com:9082/realms/DirectNexus/protocol/openid-connect/certs
server:
  port: 8081

